(()=>{
  "use strict";
  const placeholder=(label,tone="#ee7000")=>`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="${tone}"/><stop offset="1" stop-color="#171b21"/></linearGradient></defs><rect width="600" height="600" fill="url(#g)"/><path d="M0 450L600 190V600H0Z" fill="#fff" opacity=".08"/><circle cx="300" cy="250" r="108" fill="none" stroke="#fff" stroke-width="9" opacity=".74"/><text x="300" y="275" fill="#fff" font-family="Arial,sans-serif" font-size="68" font-weight="700" text-anchor="middle">${label.slice(0,2).toUpperCase()}</text></svg>`)}`;
  const highlights=[
    {id:"company",title:"Company",cover:placeholder("Company"),stories:[
      {eyebrow:"DY LIGHTS",title:"Engineering light. Powering trust.",copy:"A professional manufacturer focused on reliable LED power supplies and LED lighting solutions for global partners.",media:"/approved/hero-room-final.jpg"},
      {eyebrow:"Our approach",title:"Built around long-term partnership.",copy:"Responsive service, honest specifications and practical engineering support from product selection to delivery.",media:"/approved/dy-lights-official.jpg",fit:"contain"}]},
    {id:"factory",title:"Factory",cover:placeholder("Factory","#9a4c11"),stories:[
      {eyebrow:"Manufacturing",title:"Quality controlled at the source.",copy:"From component selection and assembly to inspection, testing and shipment preparation.",media:"/approved/hero-room-final.jpg"},
      {eyebrow:"Testing",title:"100% production testing.",copy:"Every stage is organized around stable performance, reliability and consistent factory standards.",media:"/series/rz.png",fit:"contain"}]},
    {id:"showrooms",title:"Showrooms",cover:placeholder("Showrooms","#5d6670"),stories:[
      {eyebrow:"DY LIGHTS showroom",title:"Solutions customers can see and compare.",copy:"A clear product presentation for new releases, demonstrations and technical discussions.",media:"/approved/hero-room-final.jpg"}]},
    {id:"exhibitions",title:"Exhibitions",cover:placeholder("Exhibitions","#7a5a39"),stories:[
      {eyebrow:"Global events",title:"Meeting lighting partners worldwide.",copy:"Product presentations, technical conversations and stronger relationships at international exhibitions.",media:"/approved/hero-room-final.jpg"}]},
    {id:"customers",title:"Customers",cover:placeholder("Customers","#3f5566"),stories:[
      {eyebrow:"Partnership",title:"Built for distributors and project professionals.",copy:"Long-term cooperation supported by dependable products, fast communication and practical service.",media:"/approved/hero-room-final.jpg"}]},
    {id:"quality",title:"Quality",cover:placeholder("Quality","#4d5d3d"),stories:[
      {eyebrow:"Quality comes first",title:"Engineered with care. Built to perform.",copy:"Production testing, inspection and reliability standards protect every DY LIGHTS project.",media:"/series/hp.png",fit:"contain"},
      {eyebrow:"Professional protection",title:"Designed for demanding installations.",copy:"Stable output, dependable protection and manufacturing discipline across the DY LIGHTS range.",media:"/approved/rz-400w.png",fit:"contain"}]},
    {id:"products",title:"Products",cover:placeholder("Products","#ee7000"),stories:[
      {eyebrow:"DY LIGHTS power solutions",title:"Power for every lighting application.",copy:"Indoor, waterproof, compact and professional dimming solutions in one complete range.",media:"/approved/hero-room-final.jpg"},
      {eyebrow:"HP Series",title:"Premium IP67 waterproof power.",copy:"Professional outdoor power from 100W to 1000W with a 5-year warranty.",media:"/approved/hp-400w.png",fit:"contain"},
      {eyebrow:"HL7 Series",title:"New-generation indoor power.",copy:"60–500W, DC 12V / 24V and a 3-year warranty.",media:"/products/hl7/300W-24V-HL7.png",fit:"contain"},
      {eyebrow:"AT Series",title:"Smart 2 in 1 power solution.",copy:"Automatic 12V / 24V detection for professional indoor lighting projects.",media:"/series/at.png",fit:"contain"},
      {eyebrow:"MINI Series",title:"Mini size. Big performance.",copy:"Ultra-compact power engineered for modern lighting installations.",media:"/approved/mini-60w.png",fit:"contain"},
      {eyebrow:"Dimming solutions",title:"Control built for professional projects.",copy:"Explore D, DALI and HK Series for flexible lighting control.",media:"/series/dali.png",fit:"contain"},
      {eyebrow:"Explore the complete range",title:"Find the right DY LIGHTS solution.",copy:"Compare every series, wattage and application on the existing product page.",media:"/approved/hero-room-final.jpg",cta:{label:"EXPLORE ALL PRODUCTS",href:"#products"}}]}
  ];
  let groupIndex=0,storyIndex=0,timer=null,remaining=6000,startedAt=0,paused=false,opener=null,touchX=0,savedScrollY=0;
  const q=(s,r=document)=>r.querySelector(s);
  const make=(tag,cls,attrs={})=>{const el=document.createElement(tag);if(cls)el.className=cls;Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el};
  const row=make("div","dyhl-highlights",{"aria-label":"DY LIGHTS Highlights"});
  const viewport=make("div","dyhl-highlights__viewport");
  const list=make("ul","dyhl-highlights__list");
  highlights.forEach((item,index)=>{const li=make("li");const b=make("button","dyhl-highlights__button",{type:"button","aria-label":`Open ${item.title} Highlight`});const cover=make("span","dyhl-highlights__cover");const img=make("img","",{src:item.cover,alt:"",loading:"lazy",decoding:"async"});const label=make("span","dyhl-highlights__label");label.textContent=item.title;cover.append(img);b.append(cover,label);b.addEventListener("click",()=>open(index,b));li.append(b);list.append(li)});
  viewport.append(list);row.append(viewport);
  const modal=make("div","dyhl-story",{hidden:"",role:"dialog","aria-modal":"true","aria-label":"DY LIGHTS Highlight viewer"});
  modal.innerHTML=`<div class="dyhl-story__dialog"><div class="dyhl-story__media"></div><div class="dyhl-story__top"><div class="dyhl-story__progress"></div><div class="dyhl-story__meta"><span class="dyhl-story__meta-dot"></span><span></span></div></div><button class="dyhl-story__close" type="button" aria-label="Close Highlights">×</button><button class="dyhl-story__nav dyhl-story__nav--prev" type="button" aria-label="Previous story">‹</button><button class="dyhl-story__nav dyhl-story__nav--next" type="button" aria-label="Next story">›</button><div class="dyhl-story__content"><p class="dyhl-story__eyebrow"></p><h2 class="dyhl-story__title"></h2><p class="dyhl-story__copy"></p><a class="dyhl-story__cta" hidden></a></div></div>`;
  function inject(){const sellers=q(".sellers");if(!sellers||q(".dyhl-highlights",sellers))return false;const grid=q(".seller-grid",sellers);sellers.insertBefore(row,grid);document.body.append(modal);return true}
  function render(){const group=highlights[groupIndex],story=group.stories[storyIndex],box=q(".dyhl-story__media",modal);box.replaceChildren();box.style.background=story.background||"#171b21";let mediaDuration=duration();if(story.type==="video"){const video=make("video","",{src:story.media,muted:"",playsinline:"",preload:"metadata","aria-label":story.title});video.muted=true;video.playsInline=true;video.addEventListener("loadedmetadata",()=>{if(Number.isFinite(video.duration)){mediaDuration=Math.max(1500,video.duration*1000);resetProgress(mediaDuration);startTimer(mediaDuration)}video.play().catch(()=>{})},{once:true});video.addEventListener("ended",next,{once:true});box.append(video)}else if(story.media){const image=make("img","",{src:story.media,alt:story.title,decoding:"async",loading:"eager"});image.style.objectFit=story.fit||"cover";box.append(image)}q(".dyhl-story__meta span:last-child",modal).textContent=group.title;q(".dyhl-story__eyebrow",modal).textContent=story.eyebrow;q(".dyhl-story__title",modal).textContent=story.title;q(".dyhl-story__copy",modal).textContent=story.copy;const cta=q(".dyhl-story__cta",modal);if(story.cta){cta.hidden=false;cta.textContent=story.cta.label;cta.href=story.cta.href}else{cta.hidden=true;cta.removeAttribute("href")};resetProgress(mediaDuration);startTimer(mediaDuration)}
  function resetProgress(ms){const group=highlights[groupIndex],progress=q(".dyhl-story__progress",modal);progress.replaceChildren(...group.stories.map((_,i)=>{const t=make("span",`dyhl-story__track${i<storyIndex?" is-complete":i===storyIndex?" is-active":""}`);t.style.setProperty("--dyhl-duration",`${ms}ms`);t.append(make("span","dyhl-story__fill"));return t}))}
  function duration(){return matchMedia("(prefers-reduced-motion: reduce)").matches?10000:6000}
  function startTimer(ms=duration()){clearTimeout(timer);remaining=ms;startedAt=Date.now();if(!paused)timer=setTimeout(next,ms)}
  function pause(){if(paused)return;paused=true;remaining=Math.max(300,remaining-(Date.now()-startedAt));modal.classList.add("is-paused");clearTimeout(timer);const video=q("video",modal);if(video)video.pause()}
  function resume(){if(!paused)return;paused=false;modal.classList.remove("is-paused");startTimer(remaining);const video=q("video",modal);if(video)video.play().catch(()=>{})}
  function open(index,button){groupIndex=index;storyIndex=0;opener=button;savedScrollY=window.scrollY;document.body.style.position="fixed";document.body.style.top=`-${savedScrollY}px`;document.body.style.width="100%";modal.hidden=false;document.body.classList.add("dyhl-story-open");render();q(".dyhl-story__close",modal).focus()}
  function close(){clearTimeout(timer);const video=q("video",modal);if(video)video.pause();modal.hidden=true;document.body.classList.remove("dyhl-story-open");document.body.style.position="";document.body.style.top="";document.body.style.width="";window.scrollTo(0,savedScrollY);paused=false;modal.classList.remove("is-paused");if(opener)opener.focus()}
  function next(){const stories=highlights[groupIndex].stories;if(storyIndex<stories.length-1)storyIndex++;else{groupIndex=(groupIndex+1)%highlights.length;storyIndex=0}render()}
  function prev(){if(storyIndex>0)storyIndex--;else{groupIndex=(groupIndex-1+highlights.length)%highlights.length;storyIndex=highlights[groupIndex].stories.length-1}render()}
  q(".dyhl-story__close",modal).addEventListener("click",close);q(".dyhl-story__nav--prev",modal).addEventListener("click",prev);q(".dyhl-story__nav--next",modal).addEventListener("click",next);
  modal.addEventListener("mouseenter",pause);modal.addEventListener("mouseleave",resume);modal.addEventListener("touchstart",e=>{touchX=e.changedTouches[0].clientX},{passive:true});modal.addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>45)(dx<0?next:prev)()},{passive:true});
  document.addEventListener("keydown",e=>{if(modal.hidden)return;if(e.key==="Escape")close();else if(e.key==="ArrowRight")next();else if(e.key==="ArrowLeft")prev();else if(e.key==="Tab"){const f=[...modal.querySelectorAll("button:not([hidden]),a:not([hidden])")];const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
  if(!inject()){const observer=new MutationObserver(()=>{if(inject())observer.disconnect()});observer.observe(document.documentElement,{childList:true,subtree:true})}
})();
